apiVersion: v1
kind: Service
metadata:
  name: devops-platform-svc
  namespace: devops-platform
spec:
  type: LoadBalancer      # ← change this
  selector:
    app: devops-platform-app
  ports:
  - port: 80
    targetPort: 3000
